@startuml

title Activity Diagram 

start

:User share location to program; 
:Program checks user location;

if (Is Location valid?) then (yes)
  :Give info about air;
else (no)
  :Your data is corrupted, try later!;
endif

stop

@enduml
