@startuml

title Concept of Classes Diagram 

Class Consumer
Class Clear air API
Class Google maps API
Class Location

Consumer"1" o-- "1"Location 
Google maps API"1" o-- "1"Location
Clear air API"1" o-- "1"Location

@enduml
