@startuml 
title Usecase for Information system
left to right direction
skinparam packageStyle rect

actor Consumer

rectangle {
  User --> (Share Location)
  (Send Message) ..> (Share Location) : <<include>>
  (Get info about air) ..> (Share Location) : <<include>>
  (Get nearest gyms) ..> (Share Location) : <<include>>
}
@enduml
